### ISSUE TITLE
Error when running ladder.py

### ISSUE THREAD

**Issue by lfpolani** [rinuboney/ladder#8]
I get the following error when running ladder.py. Please, advise on how to solve it. 

=== Corrupted Encoder ===
Layer  1 :  784  ->  1000
Traceback (most recent call last):
  File "ladder.py", line 138, in <module>
    y_c, corr = encoder(inputs, noise_std)
  File "ladder.py", line 93, in encoder
    m, v = tf.nn.moments(z_pre_u, axes=[0])
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn.py", line 536, in moments
    divisor *= x.get_shape()[d].value
TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType'

**Comment by rinuboney** [comment]
I thought this [issue](https://github.com/tensorflow/tensorflow/issues/139) was solved. I just found that it is still a problem when using GPUs. You can use the workaround function [here](https://github.com/tensorflow/tensorflow/issues/139) to solve it.

**Comment by lfpolani** [comment]
Thanks. I did as you suggested. However, now the execution stops after "starting session". It does not go to Training. This is what is last shown in my console:

===  Starting Session ===
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
can't determine number of CPU cores: assuming 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
W tensorflow/core/common_runtime/executor.cc:1027] 0x11474f040 Compute status: Invalid argument: You must feed a value for placeholder tensor 'Placeholder_2' with dtype bool
     [[Node: Placeholder_2 = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Traceback (most recent call last):
  File "ladder.py", line 239, in <module>
    sess.run(init)
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 345, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 419, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_2' with dtype bool
     [[Node: Placeholder_2 = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Placeholder_2', defined at:
  File "ladder.py", line 67, in <module>
    training = tf.placeholder(tf.bool)
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 651, in placeholder
    name=name)
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 463, in _placeholder
    name=name)
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 633, in apply_op
    op_def=op_def)
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/lfc009/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 988, in __init__
    self._traceback = _extract_stack()

**Comment by lfpolani** [comment]
I finally solved this and the code is running. Thanks!
